{{- if .Values.useLegacyProvisioner }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed

---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: managed-standard-hdd
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed

{{- if semverCompare ">= 1.13" .Capabilities.KubeVersion.GitVersion }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: managed-standard-ssd
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: StandardSSD_LRS
  kind: managed
{{- end }}

---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: managed-premium-ssd
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: managed

---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: files
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:azure-file-provisioner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:     ["create", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:azure-file-provisioner
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-file-provisioner
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
{{- end }}
